### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by linakherchi** [shinara03/Overnote#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
Thanks, Lena ! 

What does the Notebook Show Page hold ? If it holds the a list of notes - You will need to have NotesIndex + NotesIndexItem components under the NotebookShow frontend route.

**Comment by shinara03** [comment]
Hi, Lina! I have fixed to have NoteIndex and NoteIndexItem components under the NotebookShow!
